config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :item_carts
  resources :carts
  resources :brands
  resources :components

  devise_scope :user do
    authenticated :user do
      root "components#index"
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :user_unregistered
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item_cart.rb
class ItemCart < ActiveResource::Base
	self.site = "http://localhost:3001/"
	belongs_to :component
	belongs_to :cart

    validates :quantity, :unit_price, numericality: true
    validates :quantity, :unit_price, presence: true

	def pricetotal
        price = 0

        price = self.quantity * self.unit_price

        if self.component.rgb == true
            price = price * 1.25

        end

        price

    end

    def self.filterb_m(b_m) # FILTRA POR MODELO  O MARCA CUALQUIERA DE LAS DOS
        items = []

        b_m = b_m.downcase

        for a in ItemCart.all
            m = a.component.model.downcase
            b = a.component.brand.name.downcase

            if m.include?(b_m) or b.include?(b_m)
                count = 0
                for a2 in items
                    if a2 == a
                        count = count + 1
                    end
                end
                if count == 0
                    items.push(a)
                end
            end
        end

        items
    end

    def self.filterperprice(min, max) # FILTRA POR PRECIO USANDO LA VARIABLE DE ARRIBA QUE CALCULA EL PRECIO TOTAL
        items = []

        min = min.to_f
        max = max.to_f

        for i in ItemCart.all
            if i.pricetotal >= min and i.pricetotal <= max
                items.push(i)
            end
        end

        items

    end



end

app/controllers/item_carts_controller.rb
class ItemCartsController < ApplicationController
  before_action :set_item_cart, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /item_carts or /item_carts.json
  def index
    if params[:b_m]
      @item_carts = ItemCart.filterb_m(params[:b_m])
    elsif params[:minimum] and params[:maximum]
      @item_carts = ItemCart.filterperprice(params[:minimum], params[:maximum])
    else
      @item_carts = ItemCart.all
    end
  end

  # GET /item_carts/1 or /item_carts/1.json
  def show
  end

  # GET /item_carts/new
  def new
    @item_cart = ItemCart.new
  end

  # GET /item_carts/1/edit
  def edit
  end

  # POST /item_carts or /item_carts.json
  def create
    @item_cart = ItemCart.new(item_cart_params)

    respond_to do |format|
      if @item_cart.save
        format.html { redirect_to @item_cart, notice: "Item cart was successfully created." }
        format.json { render :show, status: :created, location: @item_cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_carts/1 or /item_carts/1.json
  def update
    respond_to do |format|
      if @item_cart.update_attributes(item_cart_params)
        format.html { redirect_to @item_cart, notice: "Item cart was successfully updated." }
        format.json { render :show, status: :ok, location: @item_cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_carts/1 or /item_carts/1.json
  def destroy
    @item_cart.destroy
    respond_to do |format|
      format.html { redirect_to item_carts_url, notice: "Item cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_cart
      @item_cart = ItemCart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_cart_params
      params.require(:item_cart).permit(:quantity, :unit_price, :component_id, :cart_id)
    end
end

app/helpers/item_carts_helper.rb
module ItemCartsHelper
end

app/views/item_carts/_form.html.erb
<%= form_with(model: item_cart) do |form| %>
  <% if item_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_cart.errors.count, "error") %> prohibited this item_cart from being saved:</h2>

      <ul>
        <% item_cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :component_id %>
    <%= form.collection_select(:component_id, Component.all.map{|a| ["#{a.model} - #{a.brand.name}", a.id] },:second,:first) %>
  </div>

  <div class="field", style="display: none">
    <%= form.label :cart_id %>
    <%= form.number_field :cart_id, :value => params[:cart_id] %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_carts/edit.html.erb
<h1>Editing Item Cart</h1>

<%= render 'form', item_cart: @item_cart %>

<%= link_to 'Show', @item_cart %> |
<%= link_to 'Back', item_carts_path %>

app/views/item_carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Carts</h1>

<form action="/item_carts" method="GET">

<!--ESTO ES BUSQUEDA BLANDA<-->
Brand or Model: <input type="b_m" name="b_m" placeholder="Brand or model" value="<%= @b_m %>"/>

<input type="submit", value="Filter" />
</form>

<form action="/item_carts" method="GET">

  MIN: <input type="text" name="minimum" placeholder="Minimum price" value="<%= @minimum %>"/>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  MAX :<input type="text" name="maximum" placeholder="Maximum price" value="<%= @maximum %>"/>

  <input type="submit", value="Filter by total price" />

</form>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Unit price</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Category</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_carts.each do |item_cart| %>
    <% if item_cart.component.rgb == true %>
      <tr style="background-color: #40FF00">
    <% else %>
      <tr>
    <% end %>
        <td><%= item_cart.quantity %></td>
        <td><%= item_cart.unit_price %></td>
        <td><%= item_cart.component.brand.name %></td>
        <td><%= item_cart.component.model %></td>
        <td><%= item_cart.component.category %></td>
        <td><%= item_cart.pricetotal %></td>
        <% if item_cart.component.rgb == true %>
          <td> + 25% </td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', item_cart %></td>
        <td><%= link_to 'Edit', edit_item_cart_path(item_cart) %></td>
        <td><%= link_to 'Destroy', item_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Cart', carts_path %>

app/views/item_carts/new.html.erb
<h1>New Item Cart</h1>

<%= render 'form', item_cart: @item_cart %>

<%= link_to 'Back', item_carts_path %>

app/views/item_carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @item_cart.quantity %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @item_cart.unit_price %>
</p>

<%= link_to 'Edit', edit_item_cart_path(@item_cart) %> |
<%= link_to 'Back', item_carts_path %>