config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :item_carts
  resources :carts
  resources :brands
  resources :components

  devise_scope :user do
    authenticated :user do
      root "components#index"
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :user_unregistered
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ActiveResource::Base
	self.site = "http://localhost:3001/"
	has_many :item_carts

    

	def finalprice
        pricetotal = 0
        for i in ItemCart.all
            if i.cart == self
                count = i.pricetotal
                pricetotal = pricetotal + count
            end
        end
        pricetotal
    end

    def self.filteruname(uname)  # FILTRA NOMBRE BUSQUEDA BLANDA
        flights = []

        uname = uname.downcase

        for v in Cart.all
            ap = v.user_name.downcase
            if ap.include?(uname)
                puts v.user_name
                flights.push(v)
            end
        end

        flights
    end

    def self.filterfromto(from, to)  # FILTRA DESDE UNA FECHA A LA OTRA
        carts = []
        if (from == "" ) or (to == "")
            carts = Cart.all
        else
            from = from.to_date
            to = to.to_date
            for v in Cart.all
                condition = 0
                if (v.bill_date.to_date > from)
                    condition = condition + 1
                end

                if (v.bill_date.to_date < to)
                    condition = condition + 1
                end

                if (condition == 2)
                    carts.push(v)
                end
            end
            carts
        end

    end

    def self.filterprice(max)  # FILTRA TODOS LOS PRECIOS QUE ESTEN POR DEBAJO DE MAX
        carts = []
        max = max.to_f
        for i in Cart.all
            if i.finalprice < max
               carts.push(i) 
            end 
        end

        carts
    end

    def self.filterbrand(brand_id) # RECORRO PARA FILTRAR POR MARCA LISTA DESPLEGABLE
        carts = []

        for c in Cart.all
            for i in ItemCart.all
                if i.cart == c and i.component.brand.id.to_i == brand_id.to_i
                    carts.push(c)
                end
            end
        end

        carts

    end

    def self.filterperunit(minimum,maximum) # RECORRO PARA FILTRAR POR MAXIMO Y MINIMO PRECIO UNITARIO
        carts = []

        minimum = minimum.to_f
        maximum = maximum.to_f

        for c in Cart.all
            for i in ItemCart.all
                if i.cart == c and i.unit_price.to_f >= minimum.to_i and i.unit_price.to_f <= maximum.to_i
                    count = 0
                    for j in carts
                        if j == c 
                            count = count + 1
                        end
                    end
                    if count = 0
                        carts.push(c)
                    end
                end
            end
        end

        carts

    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /carts or /carts.json
  def index
    if params[:uname].blank? and params[:from].blank? and params[:to].blank? and params[:max].blank? and params[:brand_id].blank? and params[:minimum].blank? and params[:maximum].blank?
      @carts = Cart.all

    elsif params[:uname]  #FILTRA POR NOMBRE ESTANDO EN BLANCO COUNTRY
      @carts = Cart.filteruname(params[:uname]) unless params[:uname].blank?

    elsif params[:from] and params[:to]
      @carts = Cart.filterfromto(params[:from], params[:to])
    
    elsif params[:max]
      @carts = Cart.filterprice(params[:max])
    elsif params[:brand_id]
      @carts = Cart.filterbrand(params[:brand_id])
    elsif params[:minimum] and params[:maximum]
      @carts = Cart.filterperunit(params[:minimum], params[:maximum])
    end

  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update_attributes(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:user_name, :user_id, :bill_date)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, :value => current_user.first_name  %>
  </div>

  <div class="field", style="display :none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :bill_date %>
    <%= form.text_field :bill_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<form action="/carts" method="GET">

<!--ESTO ES BUSQUEDA BLANDA<-->
User name: <input type="text" name="uname" placeholder="uname" value="<%= @uname %>"/>

<input type="submit", value="Filter" />
</form>


<!-- FILTRAR DESDE UNA FECHA A LA OTRA <-->
<form action="/carts" method="GET">
  FROM: <input type="date" name="from" placeholder="From" value="<%= @from %>"/>
  TO :<input type="date" name="to" placeholder="To" value="<%= @to %>"/>
  <input type="submit", value="FILTER BY DATE" />  
</form>

<form action="/carts" method="GET">

<!--ESTO ES BUSQUEDA BLANDA<-->
FILTER PRICE: <input type="text" name="max" placeholder="max" value="<%= @max %>"/>

<input type="submit", value="Filter" />
</form>

<!--ESTO ES BUSQUEDA DESPLEGABLE<-->
<form action="/carts" method="GET">

  <%= @brand_id %> <!--ESTO ES BUSQUEDA CON LISTA DESPLEGABLE<-->
          <select name="brand_id">
            <option disabled selected value> Select a Brand </option> 
            <% Brand.all.each_with_index do | t, index | %>
              <option value="<%= t.id %>" <% t.id.to_s == @brand_id ? "selected" : "" %>> <%= t.name %> - <%= t.country %> </option>
            <% end -%>
          </select>
  
  <input type="submit", value="Filter" /> 
</form>

<!--ESTO ES BUSQUEDA DE PRECIO DESDE MINIMO A MAXIMO<-->
<form action="/carts" method="GET">
  MIN: <input type="text" name="minimum" placeholder="Minimum price" value="<%= @minimum %>"/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  MAX :<input type="text" name="maximum" placeholder="Maximum price" value="<%= @maximum %>"/>
  <input type="submit", value="Filter by price per unit" />
</form>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Bill date</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user_name %></td>
        <td><%= cart.bill_date %></td>
        <td><%= cart.finalprice %></td>
        <td><%= link_to "Add Item", new_item_cart_path(:cart_id => cart.id), class: "history-but" %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @cart.user_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Bill date:</strong>
  <%= @cart.bill_date %>
</p>

<h1>Item Carts</h1>

<table>
  <thead>
    <tr>
      <th>+Adds</th>
      <th>Quantity</th>
      <th>Unit price</th>
      <th>Category</th>
      <th>Brand name</th>
      <th>Model</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% ItemCart.all.each do |item_cart| %>
    <% if item_cart.cart == @cart %>
        <% if item_cart.component.rgb == true %>
          <tr style="background-color: #40FF00">
            <td> + 25% </td>
        <% else %>
          <tr>
            <td></td>
        <% end %>
            <td><%= item_cart.quantity %></td>
            <td><%= item_cart.unit_price %></td>
            <td><%= item_cart.component.category %></td>
            <td><%= item_cart.component.brand.name %></td>
            <td><%= item_cart.component.model %></td>
            <td><%= item_cart.pricetotal %></td>
            <td><%= link_to 'Show', item_cart %></td>
            <td><%= link_to 'Edit', edit_item_cart_path(item_cart) %></td>
            <td><%= link_to 'Destroy', item_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>