config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :item_carts
  resources :carts
  resources :brands
  resources :components

  devise_scope :user do
    authenticated :user do
      root "components#index"
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :user_unregistered
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ActiveResource::Base
	self.site = "http://localhost:3001/"
	has_many :components

	validates :name, :country, presence: true
	validate :countreia

	def countreia #FILTRO PERSONALIZADO
		if self.country.downcase == "argentina"
			errors.add(:country, "No puede ser Argentina porque somos unos desgraciados")
		end
	end

	def self.filtername(name)  # FILTRA NOMBRE BUSQUEDA BLANDA
        flights = []

        name = name.downcase

        for v in Brand.all
            ap = v.name.downcase
            if ap.include?(name)
                puts v.name
                flights.push(v)
            end
        end

        flights

    end

    def self.filtercountreia(country)  # FILTRA COUNTRY BUSQUEDA BLANDA
        brands = []

        country = country.downcase

        for v in Brand.all
            ap = v.country.downcase
            if ap.include?(country)
                puts v.country
                brands.push(v)
            end
        end

        brands

    end

    def self.filterambos(name,country)  # FILTRA COUNTRY BUSQUEDA BLANDA
        brands = []

        country = country.downcase
        name = name.downcase

        for v in Brand.all
            ap = v.country.downcase
            ap1 = v.name.downcase
            if ap.include?(country) and ap1.include?(name)
                brands.push(v)       
            end
        end

        brands

    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /brands or /brands.json
  def index
    if params[:country].blank? and params[:name].blank?
      @brands = Brand.all

    elsif params[:name] and params[:country].blank?  #FILTRA POR NOMBRE ESTANDO EN BLANCO COUNTRY
      @brands = Brand.filtername(params[:name]) unless params[:name].blank?

    elsif params[:name].blank? and params[:country]   #FILTRA POR COUNTRY ESTANDO EN BLANCO NAME
      @brands = Brand.filtercountreia(params[:country]) unless params[:country].blank?

    elsif params[:name] and params[:country]   #FILTRA POR COUNTRY Y NAME JUNTOS
      @brands = Brand.filterambos(params[:name], params[:country])

    end
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update_attributes(brand_params)
        format.html { redirect_to @brand, notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :country)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<form action="/brands" method="GET">

<!--ESTO ES BUSQUEDA BLANDA<-->
Name: <input type="name" name="name" placeholder="name" value="<%= @name %>"/>  

Country: <input type="country" name="country" placeholder="country" value="<%= @country %>"/>  

<input type="submit", value="Filter" />
</form>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.country %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @brand.country %>
</p>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Type</th>
      <th>Serial number</th>
      <th>Rgb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Component.all.each do |component| %>
        <% if component.brand == @brand %>
          <tr>
            <td><%= component.brand.name %></td>
            <td><%= component.model %></td>
            <td><%= component.category %></td>
            <td><%= component.serial_number %></td>
            <td><%= component.rgb %></td>
            <td><%= link_to 'Show', component %></td>
            <td><%= link_to 'Edit', edit_component_path(component) %></td>
            <td><%= link_to 'Destroy', component, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>